#!/bin/bash
for file in ../../collected-tests/4/ITests/*-in.json
do
   temp1=$(echo $file | cut -d'-' -f1 )
   temp2=$(echo $file | cut -d'-' -f2 )
   temp3="$temp1-$temp2-out.json"
   #echo $temp1
   #echo $temp2 
   #echo $temp3 
    echo "Begin"
    ./xinterpreter < $file | diff -w - $temp3
    echo "end"
done

